AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/*'
    - '**/*.keep'
    - '**/*.md'
    - 'public/*'

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 120
